FROM registry.docker-cn.com/library/centos
MAINTAINER hellowgw

ENV SRC_PATH=/usr/local/src \
    APP_PATH=/usr/local \
    JAVA_VERSION=jdk-8u144 \
    JAVA_DIR=jdk1.8.0_144 \
    DOWNLOAD_SERVER=http://172.16.1.254/soft/java \
    # SET JAVA ENVIORMENT
    JAVA_HOME=/usr/local/jdk1.8.0_144 \
    JAVA_BIN=/usr/local/jdk1.8.0_144/bin \
    CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar \
    PATH=$PATH:\$JAVA_HOME/bin

ADD soft/CentOS-Base.repo /etc/yum.repos.d/

# SET TIMEZONE
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo 'Asia/Shanghai' >/etc/timezone  

# install java
RUN yum install -y wget \
    && cd $SRC_PATH \
    && wget $DOWNLOAD_SERVER/$JAVA_VERSION.tar.gz \
    && tar zxf $JAVA_VERSION.tar.gz -C $APP_PATH \
    && cd $APP_PATH/$JAVA_DIR/jre/lib/security \
    && sed -i 's%securerandom.source=file:/dev/urandom%securerandom.source=file:/dev/./urandom%g' java.security \
    && rm -fr $SRC_PATH/* && yum clean all 
    

CMD ["/bin/bash"]
